---
output: github_document
title: "Digitised wordlist for Seumalur (NBG 1912) derived from Stokhof and Almanar's \"Holle lists: Vocabularies in languages of Indonesia, Vol. 10/3: Islands off the west coast of Sumatra\" from 1987"
link-citations: true
bibliography: "etc/mybib.bib"
csl: "etc/apa7.csl"
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## How to cite

If you use the data in this repository, please cite the original sources [@stokhofHolleListsVocabularies1980; @1885-144589]

> Stokhof, W. A. L., & Almanar, A. E. (1987). *Holle lists: Vocabularies in languages of Indonesia, Vol. 10/3: Islands off the west coast of Sumatra: Vol. Materials in Languages of Indonesia*. Dept. of Linguistics, Research School of Pacific Studies, The Australian National University. http://hdl.handle.net/1885/144589

> Stokhof, W. A. L. (Ed.) (with Saleh-Bronkhorst, L.). (1980). *Holle lists, vocabularies in languages of Indonesia, Vol. 1: Introductory Volume: Vol. Materials in Languages of Indonesia*. Dept. of Linguistics, Research School of Pacific Studies, The Australian National University. https://doi.org/10.15144/PL-D17


and the particular [released version](https://github.com/Holle-List/seumalur1912-holle-list/releases) of this dataset [@rajegDigitisedWordlistSeumalur2025], including the interactive master Holle List [@rajegDigitisedSearchableHolle2023b]:

> Rajeg, G. P. W. (2023). *Digitised, searchable Holle List in Stokhof (1980)* (University of Oxford; Version 1.3.1) [R]. University of Oxford’s Sustainable Digital Scholarship. https://doi.org/10.25446/oxford.23205173

> Rajeg, G. P. W., Pramadicha, P. R. K., Sanjaya, M. S. K., Maheswari, L. P., & Dewijayanthi, N. D. P. (2025). *Digitised wordlist for Seumalur (NBG 1912) derived from Stokhof and Almanar’s ‘Holle lists: Vocabularies in languages of Indonesia, Vol. 10/3: Islands off the west coast of Sumatra’ from 1987* (Version 1.0.0) [Dataset]. https://github.com/Holle-List/seumalur1912-holle-list (Original work published 2025)

## Overview

<!-- badges: start -->
<!-- badges: end -->

The R code file for processing the digitised Seumalur wordlist (with Indonesian and English glosses and part of the Holle List for the Barrier Islands Languages of Sumatra, Indonesia) is available [here](https://github.com/complexico/holle-list-barrier-islands/blob/main/processing-seumalur-googlespreadsheet.R) from [this repository](https://github.com/complexico/holle-list-barrier-islands). The digitised version of the Seumalur wordlist is part of the group project in [this repository](https://github.com/complexico/lexico-holle-list-barrier-islands).

## References {-}
